proyecto/miscosas/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [

    path('logout', views.logout_view, name="logout_view"),
    path('login', views.login_view, name="login_view"),
    path('style.css', views.procesar_css, name="procesar_css"),
    path('alimentador/<str:id>', views.alimentador, name="procesar_alimentador"),
    path('item/<str:id>', views.mostrar_item, name="mostrar_item"),
    path('usuario/<str:us>', views.cuenta_usuario, name="cuenta_usuario"),
    path('alimentadores', views.alimentadores, name="alimentadores"),
    path('usuarios', views.usuarios, name="usuarios"),
    path('informacion', views.info),
    path('', views.index, name="index"),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('miscosas.urls')),
    path('admin/', admin.site.urls),
]

proyecto/miscosas/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


tamano = {'pequena':{'p': 13, 'h3': 25, 'h2':31},
            'mediana':{'p': 16, 'h3': 28, 'h2':35},
            'grande':{'p': 19, 'h3':32, 'h2': 40}
        }

estilous = {'oscuro': {'color_letra': 'white', 'fondo_cabec': 'fondo_cabecera_oscuro.jpg',
                        'fondo': 'fondo_oscuro.jpg'},
            'ligero': {'color_letra': 'black', 'fondo_cabec': 'fondo_cabecera2.jpg',
                        'fondo': 'fondo.jpg'}}
# Create your models here.
class Alimentador(models.Model):
    tipo = models.CharField(max_length=10, default="")
    nombre = models.CharField(max_length=64)
    enlace = models.TextField(default="") #al canal o al subreddit
    elegido = models.BooleanField(default=True)
    #en el caso del reddit sera igual al nombre del subrredit
    #en el caso del youtube sera el id del id_canal
    #en el caso de fm sera el nombre del artista
    id_canal = models.CharField(max_length=64, default="")
    usuario = models.ManyToManyField(User)


    def __str__(self):
        return self.nombre

    def count_likes(self):
        count = 0
        for item in self.item_set.all():
            count = item.count_likes() + count
        return count

    def total_it(self):
        return self.item_set.all().count()


class PagUsuario(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to="img_users")
    tamLetra =  models.CharField(max_length=10, default='mediana')
    estilo = models.CharField(default='ligero', max_length=100)


class Item(models.Model):
    titulo = models.CharField(max_length=64)
    enlace = models.TextField(default="")
    descrip = models.TextField(default="")
    alimentador =  models.ForeignKey(Alimentador, on_delete=models.CASCADE)
    id_item = models.CharField(max_length=20, default="")

    def __str__(self):
        return self.titulo

    def count_likes(self):
        count = 0
        for like in self.like_set.all():
            count = like.boton + count
        return count

class Comentario(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateTimeField(default=datetime.now)
    texto =  models.TextField()
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to="img_comens", blank=True)

    def __str__(self):
        return "Comentario del item:"+self.item.titulo


class Like(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, default=None)
    boton = models.IntegerField(default=0)
    fecha = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return "Like de "+ self.usuario.username +" en el item: "+self.item.titulo

proyecto/miscosas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import PagUsuario, Comentario
from django.utils.translation import gettext_lazy as _

class RegistrationForm(UserCreationForm):
    password2 = None

class PagUsForm(forms.Form):
    CHOICES = [('pequena', _('Pequeño')), ('mediana', _('Mediana')), ('grande', _('Grande'))]
    tamano = forms.ChoiceField(widget = forms.Select, choices = CHOICES, label=_('Tamaño'))
    CHOICES2 = [('oscuro', _('Oscuro')), ('ligero', _('Ligero'))]
    estilo = forms.ChoiceField(widget = forms.Select, choices = CHOICES2, label=_('Estilo'))

class AlimForm(forms.Form):
    CHOICES = [('reddit', 'Reddit'), ('yt', 'Youtube'), ('fm', 'LastFm')]
    tipo_alimentador = forms.ChoiceField(widget = forms.Select, choices = CHOICES, label=_('Tipo de alimentador'))
    identificador_o_nombre = forms.CharField(label=_('Identificador o nombre')) #este sera el nombre en el modelo


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('texto', 'foto')
        labels = {
                    'texto': _('Texto'),
                    'foto': _('Foto')
        }

class UploadImageForm(forms.ModelForm):

    class Meta:
        model = PagUsuario
        fields = ['foto']
        labels = {'foto': _('Foto') }

proyecto/miscosas/views.py
from datetime import datetime

# Create your views here.

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.template import loader
from django.template.loader import get_template
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.template import Context

from django.db.models import Sum, Count, Q, Case, When, Value
from django.db.models.functions import Coalesce
from django.utils.translation import gettext_lazy as _

#from urllib import request
import urllib.request

from .forms import RegistrationForm, PagUsForm, AlimForm, ComentarioForm, UploadImageForm
from .models import PagUsuario, tamano, estilous, Alimentador, Item, Comentario, Like
from .ytalim import YTChannel
from .redalim import SubReddit
from .fmalim import FMArtista
from .crear_docs import XML_create, JSON_create

# Create your views here.

archivo_like={1:  ['like_sel.jpg', 'dis.jpg'],
            0:  ['like.jpg', 'dis.jpg'],
            -1:  ['like.jpg', 'dis_sel.jpg'],
}

def devolver_404(request, url, context):
    resp = render(request, url, context)
    resp.status_code = 404
    return resp

def info(request):
    return render(request, 'miscosas/info.html', {'nav_info': "active", 'recurso_us': "/informacion"})

def procesar_docs_users(request, lista):
    doc = request.GET['format']
    if doc == "xml":
        return HttpResponse(XML_create().xml_users(lista)
                            , content_type="text/xml")
    elif doc == "json":
        return HttpResponse(JSON_create().json_users(lista)
                            , content_type="application/json")
    else:
        context = {'error': _("No se soporta ese tipo de documento"), 'recurso_us': '/usuarios'}
        return devolver_404(request, 'miscosas/pag_error.html', context)

def usuarios(request):
    lista = PagUsuario.objects.all()
    if 'format' in request.GET.keys():
        return procesar_docs_users(request, lista)
    context = {'lista': lista, 'recurso_us': "/usuarios", 'nav_users': 'active'}
    return render(request, 'miscosas/usuarios.html', context)

def procesar_docs_alims(request, lista):
    doc = request.GET['format']
    if doc == "xml":
        return HttpResponse(XML_create().xml_alims(lista)
                            , content_type="text/xml")
    elif doc == "json":
        return HttpResponse(JSON_create().json_alims(lista)
                            , content_type="application/json")
    else:
        context = {'error': _("No se soporta ese tipo de documento"), 'recurso_us': '/alimentadores'}
        return devolver_404(request, 'miscosas/pag_error.html', context)

def alimentadores(request):
    lista = Alimentador.objects.all()
    if 'format' in request.GET.keys():
        return procesar_docs_alims(request, lista)
    context = {'lista': lista, 'recurso_us': "/alimentadores", 'nav_alims': 'active'}
    return render(request, 'miscosas/alimentadores.html', context)

def nombre_persona(user):
    #funcion que devuelve el nombre del usuario si esta registrado
    #o el codigo de la cookie en caso de no estarlo
    if user.is_authenticated:
        return user
    else:
        return ""

def guardar_us_enalim(user, id):
    #funcion que guarda el usuario al que le ha dado a elegir al alimentador
    alim = Alimentador.objects.get(id=id)
    if nombre_persona(user) != "":
        alim.usuario.add(nombre_persona(user))

def leer_xml(tipo, nombre):
    if tipo == "yt":
        id = YTChannel(nombre).id_canal()
    elif tipo == "reddit":
        id = SubReddit(nombre).id_reddit()
    elif tipo == "fm":
        id = FMArtista(nombre).id_artista()
    return id

def gestionar_alims(request):
    form = AlimForm(request.POST)
    if not form.is_valid():
         return -1

    tipo = form.cleaned_data['tipo_alimentador']
    nombre = form.cleaned_data['identificador_o_nombre']

    return leer_xml(tipo, nombre)
#if 'enviar' in request.GET:
    #return redirect('/alimentador/'+str(alim.id))
#un solo boton
#elegio = False --> elegido= True, #añado a la lista de usuarios, actualizar datos
#elegido = True--> elegido = False,
def procesar_docs_alim(request, alim):
    doc = request.GET['format']
    if doc == "xml":
        return HttpResponse(XML_create().xml_alim(alim)
                            , content_type="text/xml")
    elif doc == "json":
        return HttpResponse(JSON_create().json_alim(alim)
                            , content_type="application/json")
    else:
        context = {'error': _("No se soporta ese tipo de documento"), 'recurso_us': '/alimentador'+str(alim.id)}
        return devolver_404(request, 'miscosas/pag_error.html', context)

def alimentador(request, id=-1):
    if request.method == "POST":
        id = gestionar_alims(request)
        if id == -1:
            context = {'error': _("No se ha podido encontrar la URL para ese alimentador"),
                        'recurso_us': '/'}
            return devolver_404(request, 'miscosas/pag_error.html', context)
        else:
            guardar_us_enalim(request.user, id)
        return redirect('/alimentador/'+str(id))

    try:
        alim = Alimentador.objects.get(id=id)
    except ObjectDoesNotExist:
        context = {'error': _("El alimentador pedido no se encuentra"),
                'recurso_us': '/'}
        return devolver_404(request, 'miscosas/pag_error.html', context)

    if 'format' in request.GET.keys():
        return procesar_docs_alim(request, alim)

    context = {'alim': alim, 'recurso_us': '/alimentador/'+str(alim.id)}
    return render(request, 'miscosas/alimentador.html', context)

def gestionar_voto(action, request, item):
    if action == "like":
        num =  1
    elif action == "dislike":
        num = -1
    try:
        voto = Like.objects.get(usuario=request.user, item=item)
        if voto.boton != num:
            voto.boton = num
            voto.fecha = datetime.now()
    except ObjectDoesNotExist:
        voto = Like(usuario=request.user, item=item, boton=num)
    voto.save()

def gestionar_comen(request, item):
    form = ComentarioForm(request.POST, request.FILES)
    if form.is_valid():
        comen = Comentario(texto= form.cleaned_data['texto'], usuario=request.user,
                            item=item, foto=form.cleaned_data['foto'])
        comen.save()

def iluminar_voto(request, item):
    if request.user.is_authenticated:
        try:
            valor = request.user.like_set.get(item=item).boton
        except ObjectDoesNotExist:
            valor = 0
    else:
        valor = 0

    return archivo_like[valor][0], archivo_like[valor][1]

def procesar_docs_item(request, item):
    doc = request.GET['format']
    if doc == "xml":
        return HttpResponse(XML_create().xml_item(item)
                            , content_type="text/xml")
    elif doc == "json":
        return HttpResponse(JSON_create().json_item(item)
                            , content_type="application/json")
    else:
        context = {'error': _("No se soporta ese tipo de documento"), 'recurso_us': '/alimentador'+str(item.id)}
        return devolver_404(request, 'miscosas/pag_error.html', context)

def mostrar_item(request, id):
    try:
        item = Item.objects.get(id=id)
    except ObjectDoesNotExist:
        context = {"error": _("El item pedido no existe"), 'recurso_us': '/'}
        return devolver_404(request, 'miscosas/pag_error.html', context)

    if request.method == "POST":
        action = request.POST['action']
        if action=="comentario":
            gestionar_comen(request, item)
        elif action=="like" or action =="dislike":
            gestionar_voto(action, request, item)

    if 'format' in request.GET.keys():
        return procesar_docs_item(request, item)

    boton_like, boton_dislike = iluminar_voto(request, item)
    lista = Comentario.objects.filter(item=item)
    context = {'item': item, 'recurso_us': '/item/'+str(item.id),
                'lista': lista, 'user': request.user, 'form': ComentarioForm(),
                'boton_like': boton_like, 'boton_dislike': boton_dislike}
    return render(request, 'miscosas/item.html', context)

def add_boton_voto(top, request):
    for it in top:
        it.boton_like, it.boton_dislike = iluminar_voto(request, it)

def procesar_post_index(request):
    action = request.POST['action']
    if action == "elegir":
        alim = Alimentador.objects.get(id=request.POST['alim'])
        id = leer_xml(alim.tipo, alim.id_canal)
        alim.elegido = True
        alim.save()
        if id != -1:
            guardar_us_enalim(request.user, id)
        return redirect('/alimentador/'+str(alim.id))
    elif action == "eliminar":
        alim = Alimentador.objects.get(id=request.POST['alim'])
        alim.elegido = False
        alim.save()
        if 'enviar' in request.GET:
            return redirect('/alimentador/'+str(alim.id))
    elif action == "like" or action == "dislike":
        item = Item.objects.get(id=request.POST['item'])
        gestionar_voto(action, request, item)

    return redirect('/')

def procesar_docs(request, top10, top5, lista):
    doc = request.GET['format']
    if doc == "xml":
        return HttpResponse(XML_create().xml_index(top10, top5, lista)
                            , content_type="text/xml")
    elif doc == "json":
        return HttpResponse(JSON_create().json_index(top10, top5, lista)
                            , content_type="application/json")
    else:
        context = {'error': _("No se soporta ese tipo de documento"), 'recurso_us': '/'}
        return devolver_404(request, 'miscosas/pag_error.html', context)

def index(request):

proyecto/miscosas/templates/miscosas/alimentador.html
{% extends 'miscosas/base.html' %}
{%load i18n%}

{% block contenido %}
        <div id="presentacion_alim">
            <h2>{% trans 'Nombre' %}: {{alim.nombre}}, <a href="{{alim.enlace}}">(Link)</a></h2>
            <form method="POST" action="/?enviar=alimentador">
              {% csrf_token %}
              <input type="hidden" name="alim" value="{{alim.id}}" >
                {%if alim.elegido%}
                        <button type="submit" name= "action" value="eliminar"class="save btn btn-info">{% trans 'Eliminar' %}</button>
                {%else%}
                        <button type="submit" name= "action" value="elegir"class="save btn btn-info">{% trans 'Elegir' %}</button>
                {%endif%}
            </form>

          </div>
        <div id="lista_items">
            <h3> {% trans 'Lista de items' %}: </h3>
                {% for item in alim.item_set.all %}
                    <p><li><a href="{{item.enlace}}">{{item.titulo}}</a> <a href="/item/{{item.id}}">({% trans 'detalle' %})</a></li></p>
                    <p>(Id: {{item.id}})</p>
                  {% endfor %}
          </div>


{% endblock %}

proyecto/miscosas/templates/miscosas/alimentadores.html
{% extends 'miscosas/base.html' %}
{%load i18n%}

{% load static %}

{% block contenido %}
    <h2>{% trans 'Lista de alimentadores' %}</h2>
    {% for alim in lista %}
        <h3> - {% trans 'Nombre' %}: <a href="{{alimen.enlace}}">{{alim.nombre}}</a>, <a href="/alimentador/{{alim.id}}">({% trans 'detalle' %})</a></h3>
        <p>{% trans 'Número de ítems de este alimentador' %}: {{alim.total_it}}</p>
        <p>{% trans 'Puntuación total' %}: {{alim.count_likes}}</p>
    {% endfor  %}

{% endblock %}

proyecto/miscosas/templates/miscosas/base.html
{% load static %}
{%load i18n%}
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{%  static 'miscosas/favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'miscosas/bootstrap.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'miscosas/micss.css' %}"> -->
    <link href="/style.css" rel="stylesheet" type="text/css">

    <title>{% trans 'Mis Cosas Web' %}</title>
  </head>
  <body>
    <div id="cabecera" class="row">
      <!-- imagen del sitio #2d6360;-->
      <div id="banner" class="col-xs-3 col-md-3 col-lg-3 col-sm-3">
        <img src="{% static "miscosas/banner2.jpg" %}" width="186" height="150" align="left">
      </div>
        <div id="titulo" class="col-xs-5 col-md-5 col-lg-5 col-sm-5">
        <h1>{% trans 'MIS COSAS WEB' %}</h1>
        </div>
        <div id="caja_log" class="col-xs-4 col-md-4 col-lg-4 col-sm-4">
          <h2>{% trans 'BIENVENIDO' %}</h2>
          <!-- <p>{{error}}</p> -->
          {% if user.is_authenticated %}
                 <h2>{{user.username}}
                 <a href="/logout?recurso={{recurso_us}}">Logout</a></h2>
          {% else %}

               <form method="POST" action="/login?recurso={{recurso_us}}">
                  {% csrf_token %}

                 <input class="textbox" type="text" name="username" placeholder="Username" style = "margin-bottom: 5">
                  <input class="textbox" type="password" name="password" placeholder={% trans "Contraseña"%} style = "margin-bottom: 5">
                  <div>
                    <button type="submit" name ="action" value="Login">Login</button>
                     <button type="submit" name="action" value="Registrar">{% trans 'Registrar' %}</button>
                  </div>
                </form>
            {% endif %}
            </div>
    </div>
    <div class="nav nav-pills">
      <li class="nav-item">
        <a class="nav-link {{nav_index}}" href="/">{% trans 'Inicio' %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {{nav_alims}}" href="/alimentadores">{% trans 'Alimentadores' %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {{nav_users}}" href="/usuarios">{% trans 'Usuarios' %}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {{nav_info}}" href="/informacion">{% trans 'Información' %}</a>
      </li>
    </div>
    <div id="contenido">

        {% block contenido %}
        {% endblock %}
    </div>
    <div id="footer">
      <footer >
        <h5> {% trans 'Esta aplicación utiliza los datos proporcionados por' %}:
          <a href="https://www.reddit.com/">Reddit</a>
          <a href="https://www.youtube.com/">Youtube</a>
          <a href="https://www.last.fm/es/home">LastFM</a>

        </h5>
        <h5> {% trans 'Página web escrita por Meritxell Díaz para la asignatura de SAT' %}</h5>
      </footer>
    </div>
    </body>
</html>

proyecto/miscosas/templates/miscosas/index.html
{% extends 'miscosas/base.html' %}
{% load static %}
{%load i18n%}

    {% block contenido %}

  <div class="row">
    <div id="prim_col" class="col-xs-12 col-md-8 col-lg-8 col-sm-8">
    <div id="top10">
      <h2>{%trans 'Top 10 ítems más votados:' %}</h2>
      <p>({% trans 'Ordenados empezando por el más votado' %})</p>
          {% for item in top10 %}
                <p><li><a href="{{item.enlace}}">{{item.titulo}}</a> <a href="/item/{{item.id}}">({%trans 'detalle' %})</a></li></p>
                <p>(Id: {{item.id}})</p>
                 <p>Likes: {{item.npos}}</p>
                 <p>Dislikes: {{item.nneg}}</p>
                 {% if user.is_authenticated %}
                 <div id="voto_index">
                   <form method="POST" action="/">
                     {% csrf_token %}
                      <input type="hidden" name="item" value="{{item.id}}" >
                       <button type="submit" name= "action" value="like" class="save btn btn-info"><img src = '{% static '/miscosas/'%}{{item.boton_like}}' width="30" height="15"></button>
                       <button type="submit" name= "action" value="dislike" class="save btn btn-info"><img src = '{% static '/miscosas/'%}{{item.boton_dislike}}' width="30" height="15"></button>
                     </form>
                  </div>
                  {% endif%}
          {% endfor %}
      </div>
      <div id="alimentador_index">
        <h2>{%trans 'Alimentadores seleccionados:' %}</h2>
        {% for alim in alims %}
              <h3> -{% trans 'Nombre' %}: <a href="{{alimen.enlace}}">{{alim.nombre}}</a>, <a href="/alimentador/{{alim.id}}">({%trans 'detalle' %})</a></h3>
              <p>{%trans 'Número de ítems de este alimentador:' %} {{alim.total_it}}</p>
              <p>{%trans 'Puntuación total del alimentador:' %} {{alim.count_likes}}</p>
              <p> (Id: {{alim.id}})</p>
              <form method="POST" action="/">
                {% csrf_token %}
                    <input type="hidden" name="alim" value="{{alim.id}}" >
                    <button type="submit" name= "action" value="elegir"class="save btn btn-info">{%trans 'Elegir' %}</button>
                    <button type="submit" name= "action" value="eliminar"class="save btn btn-info">{%trans 'Eliminar' %}</button>
              </form>
        {% endfor  %}
      </div>
      </div>

      <div id="seg_col" class="col mini-box col mini-box col-xs-12 col-md-4 col-lg-4 col-sm-4">
        <div id="formalimentadores" class="row float-right" >
          <form method="POST" action="/alimentador/-1">
            <h3>{%trans 'Formulario de alimentadores:'%}</h3>
            {% csrf_token %}
            {{form.as_p}}
            <!-- <input class="textbox" type="text" name="referencia del formulario" placeholder="Identificador"> -->
            <button type="submit" action="enviar">{%trans 'Elegir alimentador'%}</button>
          </form>
        </div>
        {% if user.is_authenticated %}
        <div id="top5" class="row float-right">
          <h2>{%trans 'Top 5 últimos ítems votados:' %}</h2>
              {% if top5 %}
                    {% for item in top5 %}
                        <p><li><a href="{{item.enlace}}">{{item.titulo}}</a> <a href="/item/{{item.id}}">({%trans 'detalle' %})</a></li></p>
                            <form method="POST" action="/">
                              {% csrf_token %}
                              <input type="hidden" name="item" value="{{item.id}}" >
                              <button type="submit" name= "action" value="like" class="save btn btn-info"><img src = '{% static '/miscosas/'%}{{item.boton_like}}' width="30" height="15"></button>
                              <button type="submit" name= "action" value="dislike" class="save btn btn-info"><img src = '{% static '/miscosas/'%}{{item.boton_dislike}}' width="30" height="15"></button>
                            </form>

                    {% endfor%}
                {%else%}
                    <p> {% trans 'Vacío' %} </p>
                {%endif%}
            </div>
        {% endif%}
        </div>
      </div>
    {% endblock %}

proyecto/miscosas/templates/miscosas/info.html
{% extends 'miscosas/base.html' %}
{%load i18n%}

    {% block contenido %}
      <h2> {% trans 'Información' %}</h2>
      <h3> {% trans 'Página web escrita por Meritxell Díaz Coque para la asignatura de SAT. Doble grado: GITT+IAA' %}</h3>
      <h3> {% trans 'Funcionamiento' %}</h3>
      <p> {% trans 'Esta aplicación usa los datos del XML de las páginas web que se indican en el footer. Se distingue entre alimentadores, que pueden ser canales de youtube, subrredits o un artista. Cada alimentador tiene asociado unos items, en este caso pueden ser videos, noticias o albumes, respectivamente. Tenemos varios recursos:' %}</p>
      <br></br>
      <p> {% trans '- La página principal nos muestra los 10 items más votados en la aplicación, el formulario para introducir un alimentador y los alimentadores seleccionados por cualquier usuario. Además, si el usuario está autenticado, se mostrará el top5 de sus items votados más recientes. Además, cada alimentador de la lista anterior, aparecerá con dos botones, uno para elegirlo (lo que implica volver a leer su XML) y otro para eliminarlo de esta lista' %}</p>
      <p> {% trans '- La página de alimentadores nos muestra todos los alimentadores de los que se ha descargado información alguna vez' %}</p>
      <p> {% trans '- La página de usuarios que muestra la lista de todos los usuarios con cuenta de la aplicación.' %}</p>
      <p> {% trans '- La página de cada usuario, que muestra su foto de perfil, items comentados y votados, y los alimentadores que haya seleccionado alguna vez. Además, si el usuario que está visitando esta página coincide con el que está registrado, podrá cambiar la foto de perfil y formato de visualización de la aplicación, esto es el estilo y el tamaño.' %}</p>
      <p> {% trans '- La página de cada alimentador, que muestra un botón elimiar para borrar dicho alimentador del listado de la página principal, si estaba elegido. O lo elige, lo que conlleva actualizar sus datos y que ya aparece en la página principal, en el caso de que estuviese eliminado. Además, aparece el listado de items asociados a dicho alimentador.' %}</p>
      <p> {% trans '- La página de cada item, en el que se muestra su nombre, información del alimentador asociado, lista de comentarios de los usuarios, una descripción, y el vídeo empotrado en el caso de Youtube, o una imagen del álbum del artista en el caso de LastFM. Si además, el usuario que visita esta página está registrado, podrá votar y comentar el item' %}</p>

    {%endblock%}

proyecto/miscosas/templates/miscosas/pag_error.html
{% extends 'miscosas/base.html' %}
{%load i18n%}

{% load static %}

{% block contenido %}
      <div class='alert alert-info'>
        {{ error }}
      </div>
      <p> <a href="/">{% trans 'Pulsa aquí para volver a la página principal' %}</a></p>

{% endblock %}

proyecto/miscosas/templates/miscosas/usuarios.html
{% extends 'miscosas/base.html' %}
{%load i18n%}

{% load static %}

{% block contenido %}

    <h2>{% trans 'Lista de usuarios con cuenta' %}</h2>
    {% for pag in lista %}
        <div id="usuario">
          <h3> - {% trans 'Nombre' %}: <a href="/usuario/{{pag.usuario.username}}">{{pag.usuario.username}}</a></h3>
            {%if pag.foto%}
              <img src='{% static '/miscosas/'%}{{pag.foto.url}}'  width="80" height="75" align="left">
            {%endif %}

            <p>{% trans 'Ítems votados' %}: {{pag.usuario.like_set.all.count}}</p>
            <p> {% trans 'Comentarios realizados' %}: {{pag.usuario.comentario_set.all.count}}</p>
          </div>
    {% endfor  %}

{% endblock %}